set(ENV{RAPIDXML_ROOT} ${CMAKE_CURRENT_LIST_DIR}/rapidxml/rapidxml-1.13)
set(ENV{TBB_ROOT} ${CMAKE_CURRENT_LIST_DIR}/tbb/tbb2017_20161128oss)
set(ENV{SWIG_ROOT} ${CMAKE_CURRENT_LIST_DIR}/swig/swigwin-3.0.10)
set(ENV{MSGPACK_ROOT} ${CMAKE_CURRENT_LIST_DIR}/msgpack/msgpack-2.1.1)

if (CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ENV{ICONV_ROOT} ${CMAKE_CURRENT_LIST_DIR}/libiconv/libiconv-1.13.1-win64-20100707)
else()
    set(ENV{ICONV_ROOT} ${CMAKE_CURRENT_LIST_DIR}/libiconv/libiconv-1.9.2-1)
endif()
